import type { Metadata } from "next";
import { Geist, Inter } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import Footer from "@/components/ui/footer";
import Navigation from "@/components/ui/navigation";
import { getCartItemsByIdParams } from "@/lib/db/carts-db";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const cartId = cookieStore.get("cartId")?.value as string;
  let cartItems = [];
  if (cartId) {
    cartItems = await getCartItemsByIdParams(`_cartId=${cartId}`);
  }
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased `}>
        <div className="min-h-screen grid grid-rows-[auto_1fr_auto]">
          <Navigation cartItemsLength={cartItems?.length} />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
